### ISSUE TITLE
Error Loading color scheme in version 3.0.0

### ISSUE THREAD

**Issue by soumya997** [SublimeText-Markdown/MarkdownEditing#622]
`MarkdownEditing` previously had a certain color scheme set for it, but after the auto update to `v3.0.0`, the extension is showing this error whenever I try opening a markdown file. Can anybody please help me with this, how to activate the theme again?
<br>

<p align="center">
<img width="500" height="250" src="https://user-images.githubusercontent.com/54326088/133108010-6bea0d85-17c7-48be-8969-72be28b11dad.png">
</p>

**Comment by deathaxe** [comment]
Those still exist, but have been converted to `sublime-color-scheme` format and moved into a sub folder.

You might want to run `MarkdownEditing: Select Color Scheme` to select the converted one. This command will set a syntax specific color scheme for Markdown as it used to in earlier releases.

It should call this command automatically after install or upgrade, but I have a feeling it might not work if MDE runs on python 3.8 plugin host of ST4.

**Comment by soumya997** [comment]
@deathaxe I am only getting these three option by typing `MarkdownEditing` in the command palette.

<br>

<p align="center">
<img width="500" src="https://user-images.githubusercontent.com/54326088/133118642-d5e014d5-65bc-411a-b7dd-def1d13bd35f.png">
</p>

And seems like the `Select Color Scheme` option got disabled somehow,

<br>

<p align="center">
<img width="500" src="https://user-images.githubusercontent.com/54326088/133119004-44a27927-2bdf-4014-ada3-1e61bc15d49d.png">
</p>

**Comment by deathaxe** [comment]
Have you re-started ST after upgrade?

If so, can you check console for any error messages during startup?

It appears none of the plugins has been loaded.

**Comment by soumya997** [comment]
When I opened ST, it automatically upgraded `MarkdownEditing`, and when I tried to open a md file it showed that error, I guess after that I re-started ST few times.
yeah there are some error messages,

```
Anaconda can not spawn a new process with your current configured python interpreter (C:\Users\USER\AppData\Local\Programs\Python\Python37)

Make sure your interpreter is a valid binary and is in your PATH or use an absolute path to it, for example: C:\\Python27\\python.exe
 ...last message repeated one more time in the last 10s
ERROR:root:Your operating system denied the spawn of c:\Users\USER\AppData\Local\Programs\Python\Python37 process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
The OS did return [WinError 5] Access is denied
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_process.LocalProcess object at 0x0000029AB47EEF98> process can not start a new anaconda JsonServer in the operating system because:
```
But there is no error message regarding `MarkdownEditing`, it was showing `reloading`, and I guess it got reloaded correctly.

<br>

<p align="center">
<img width="500" src="https://user-images.githubusercontent.com/54326088/133120890-23f7630b-6d6b-4551-9209-b71c26f1cb1f.png">
</p>

**Comment by soumya997** [comment]
Ok, the problem is now fixed, actually in the `Markdown.sublime-settings` file, the location of the previously selected theme was present, I commented it out and everything is back to normal.

<br>

<p align="center">
<img width="700" src="https://user-images.githubusercontent.com/54326088/133122449-979e92b6-2242-4d39-bc77-542e428f05d7.png">
</p>

**Comment by deathaxe** [comment]
Yeah, you might need to go through those various syntax specific settings in _Packages/User/_ to tidy them.

This doesn't happen automatically to not break any user settings, but that's mensioned at https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting

> Thus all user specific syntax specific settings or overrides can or must be removed:

**Comment by deathaxe** [comment]
Next bugfix release should make bootstrapping a bit more robust, which should help re-assigning color schemes and syntaxes upon startup more reliably.

**Comment by soumya997** [comment]
yeah, that would be great.
btw, after commenting that part, everything started acting normal and I was able to to assign a new color scheme.

**Comment by Gabriel-p** [comment]
I re-installed the package and I'm still getting the error. The console shows:

```
Unable to open /home/gabriel/.config/sublime-text/Packages/MarkdownEditing/Distraction Free.sublime-settings
Unable to open /home/gabriel/.config/sublime-text/Packages/User/Distraction Free.sublime-settings
Unable to open /home/gabriel/.config/sublime-text/Packages/MarkdownEditing/Preferences.sublime-settings
```

and when i try to open the Settings file for the package, it opens instead the `Preferences.sublime.settings` file.

**Comment by deathaxe** [comment]
Unfortunatelly MDE's bootstrapper is designed to reassign default Markdown syntax, but it's not aware of the syntax to have been moved within this package. The hard way was to close all related views and reopen them, or you could run `view.assign_syntax("Packages/MarkdownEditing/syntaxes/MultiMarkdown.sublime-syntax")` for each of them via ST's console. I'll try to fix that behavior in a future release.

All MarkdownEditing related settings are organized in _Preferences.sublime-settings_ now. This way each of those settings can be global, per project or per view.
